name: puchitalks_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

  agora_rtc_engine: ^4.0.6
  provider: ^5.0.0
  state_notifier: ^0.7.0
  freezed: ^0.14.0+1
  flutter_state_notifier: ^0.7.0
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.9.1
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - .env
