name: Flutter Pub Get

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clone the repository
        run: git clone https://github.com/flutter/flutter.git

      - name: Export path
        run: |
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Install packages dependencies
        run: |
          flutter pub get
